### ISSUE TITLE
Will the codes for demo and for iterative training be released?

### ISSUE THREAD

**Issue by LihaoWang1991** [shiyinzhang/Inside-Outside-Guidance#3]
Hi IOG is very impressive job and congratulations!

I note that there is no demo code for visualizing results on 1 single image. And in the training code the input are only 3 points (2 for bounding box and 1 center point) but no extra inside or outside points for the iterative training which is mentioned in the paper. Would this part of code also be released in the future? 

Thank you.

**Comment by shiyinzhang** [comment]
We will release this part of code.

**Comment by bearpaw** [comment]
Congrats to the work and thanks for the repo! Do you any idea when the interactive demo would be available?

**Comment by shiyinzhang** [comment]
> Congrats to the work and thanks for the repo! Do you any idea when the interactive demo would be available?

We will release the demo as soon as possible. Please stay tuned.

**Comment by leemengxing** [comment]
Congrats to the work and thanks for the repo! I also hope ui demo coming soon.

**Comment by zhixuanli** [comment]
Hoping for UI demo. Thanks a lot.

**Comment by SB2020-eye** [comment]
Hi. Was this released? I'm unsure how to run the annotator gui.
